# making Linear Regression

In [15]:
import numpy as np

In [16]:
class LinearRegression:
    def __init__(self, learning_rate = 0.01 , n_iterations = 1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None
    def fit(self, X, y): # x_train & y_train
        #step 1
        m, n = X.shape # m = number of samples, n = number of features
        self.bias = 0
        self.weights = np.zeros(n) 
        for i in range(self.n_iterations):
            # step 2
            y_pred = self.bias + np.dot(X,self.weights)
            # step 3
            db = (1/m) * np.sum(y_pred - y)
            dw = (1/m) * np.dot(X.T, (y_pred - y))
            #step 4
            self.bias -= self.learning_rate * db
            self.weights -= self.learning_rate * dw 
    def predict(self, X):
        y_pred = self.bias + np.dot(X,self.weights)
        return y_pred

In [17]:
X = np.array([[1],[2],[3],[4],[5]])
y = np.array([2,4,6,8,10])
model = LinearRegression()
model.fit(X,y)
y_pred = model.predict(X)
print(y_pred)
print(model.weights)
print(model.bias)

[2.06850809 4.04226297 6.01601785 7.98977273 9.96352761]
[1.97375488]
0.09475321533750963


# making Logistic Regression

In [34]:
class LogisticRegression:
    def __init__(self, learning_rate = 0.1, n_iter=1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter
    def sigmoid(self,z):
        return (1/(1+np.exp(-z)))
    def fit(self,X,y):
        m,n = X.shape

        self.bias = 0
        self.weights = np.zeros(n)

        for i in range(self.n_iter):
            z = self.bias + np.dot(X,self.weights)
            y_pred = self.sigmoid(z)

            db = (1/m) * np.sum(y_pred- y)
            dw = (1/m) * np.dot(X.T, (y_pred - y))

            self.bias -= self.lr * db
            self.weights -= self.lr * dw
    def get_probabilities(self, X):
        z = self.bias + np.dot(X, self.weights)
        return self.sigmoid(z)
    def predict(self,X, threshold =0.5):
        probabilities = self.get_probabilities(X)
        y_pred_bool = probabilities >= threshold
        return y_pred_bool.astype(int)

In [35]:
X = np.array([[1,2],[2,3],[3,4],[4,5]])
y = np.array([0,0,1,1])
model = LogisticRegression()
model.fit(X,y)
y_pred = model.predict(X)
print(y_pred)
print(model.get_probabilities(X))

[0 0 1 1]
[0.02871674 0.26532955 0.81521201 0.98178143]


# making KNN

In [43]:
class KNNClassifier:
    def __init__(self,k=3):
        self.k = k
    def euclidean_dist(self, x1, x2):
        return np.sqrt(np.sum((x1-x2)**2))
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
    def predict_one(self,x):
        distances = [self.euclidean_dist(x,x_train) for x_train in self.X_train]
        knn_indices = np.argsort(distances)[:self.k]

        knn_classes = [self.y_train[i] for i in knn_indices]

        majority_class = np.argmax(np.bincount(knn_classes))
        return majority_class
    def predict(self, X):
        y_pred = [self.predict_one(x) for x in X] 
        return np.array(y_pred)


In [44]:
X_train = np.array([
    [1,2],
    [2,3],
    [3,3],
    [6,5],
    [7,7]
])

y_train = np.array([0,0,0,1,1])

X_test = np.array([
    [2,2],
    [6,6]
])

model = KNNClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)


[0 1]
